// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Jamiat_web.Models
{
    public partial class GetHalqaMembersResult
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Association { get; set; }
        public string Responsibility { get; set; }
    }
}
