// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Jamiat_web.Models
{
    public partial class GetMenusResult
    {
        public int ID { get; set; }
        public string Menu { get; set; }
        public string URL { get; set; }
        public bool? IsParent { get; set; }
    }
}
