// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jamiat_web.Models
{
    public partial class Halqa
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Ilaqa { get; set; }

        public virtual Ilaqa IlaqaNavigation { get; set; }
    }
}