// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Jamiat_web.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Jamiat_web.Models
{
    public partial interface IJamiatContextProcedures
    {
        Task<List<GetHalqaMembersResult>> GetHalqaMembersAsync(string halqaId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetMenusResult>> GetMenusAsync(int? UserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
