// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jamiat_web.Models
{
    public partial class Ilaqa
    {
        public Ilaqa()
        {
            Halqa = new HashSet<Halqa>();
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public string Zone { get; set; }

        public virtual Zones ZoneNavigation { get; set; }
        public virtual ICollection<Halqa> Halqa { get; set; }
    }
}