// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jamiat_web.Models
{
    public partial class MenuMappings
    {
        public int Id { get; set; }
        public int MasterId { get; set; }
        public int MenuId { get; set; }
        public DateTime EntryDate { get; set; }

        public virtual MenuMappingMaster Master { get; set; }
        public virtual Menus Menu { get; set; }
    }
}