// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jamiat_web.Models
{
    public partial class UserRespMapping
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int RespId { get; set; }
        public string RespLevel { get; set; }

        public virtual Responsibilities Resp { get; set; }
        public virtual Users User { get; set; }
    }
}