// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jamiat_web.Models
{
    public partial class Zones
    {
        public Zones()
        {
            Ilaqa = new HashSet<Ilaqa>();
        }

        public string Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Ilaqa> Ilaqa { get; set; }
    }
}